---
- name: Provision EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    instance_type: t3.medium
    security_group: my-security-group
    image: ami-0c41531b8d18cc72b
    region: us-east-1
    key_name: sa-aaponaws-mar2023
    count: 1

  tasks:
    - name: Create a new security group
      ec2_group:
        name: "{{ security_group }}"
        description: "Security group for EC2 instance"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: ec2_security_group

    - name: Launch a new EC2 instance
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        group_id: "{{ ec2_security_group.group_id }}"
        count: "{{ count }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        wait: true
      register: ec2_instance
