---
- name: Install JBoss EAP on RHEL 9
  hosts: 10.1.0.64
  become: yes

  tasks:
  - name: Update the package cache
    dnf:
      update_cache: yes

  - name: Install the required dependencies for JBoss EAP
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - java-11-openjdk-devel
      - unzip
      - wget

  - name: Download JBoss EAP 7.4.0
    get_url:
      url: "https://access.cdn.redhat.com/content/origin/files/sha256/5f/5f1f0b7a389dedcd6f91ea3c8c6c9b723e9e8609bdf5720d4088e5469d46ad3a/jboss-eap-7.4.0.zip?_auth_=1680706091_c7c6dbd616dbf5988601cd0582594857"
      dest: "/home/ec2-user"
      mode: '0644'

  - name: Extract the JBoss EAP archive
    unarchive:
      src: "/home/ec2-user/jboss-eap-7.4.0.zip"
      dest: "/home/ec2-user"
      remote_src: yes
      

  - name: Start JBoss EAP server
    command: "/home/ec2-user/jboss-eap-8.0/bin/standalone.sh -b 0.0.0.0"
    
