- name: JBoss EAP installation
  hosts: 10.1.0.30
  become: true
  tasks:
    #- name: Download JBoss EAP binaries
    #  get_url:
    #    url: https://access.cdn.redhat.com/content/origin/files/sha256/5f/5f1f0b7a389dedcd6f91ea3c8c6c9b723e9e8609bdf5720d4088e5469d46ad3a/jboss-eap-7.4.0.zip?_auth_=1680499607_b3ead5edf3e80af88d73d19b4cc96de8
    #    url_username: rh-ee-saraavin
    #    url_password: A9772376s12!
    #    dest: /home/ec2-user/opt

    - name: Unzip the downloaded ZIP file
      unarchive:
        src: /home/ec2-user/opt/jboss-eap-7.4.0.zip
        dest: /home/ec2-user/opt
        remote_src: yes

    - name: Create JBoss EAP user
      user:
        name: jboss-user
        group: jboss-user
        password: pa$$w0rd
        home: /home/ec2-user/opt/jboss-eap-7.4.0
        shell: "/bin/bash"

    - name: Change owner & group of JBoss EAP directory
      file:
        path: /home/ec2-user/opt/jboss-eap-7.4.0
        owner: jboss-user
        group: jboss-user
        recurse: yes

    - name: Edit JBoss EAP configuration file
      lineinfile:
        state: present
        path: /home/ec2-user/opt/jboss-eap-7.4.0/bin/init.d/jboss-eap.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - {regexp: "^# JAVA_HOME=", line: 'JAVA_HOME="/home/ec2-user/opt/jdk-18.0.2.1"'}
        - {regexp: "^# JBOSS_HOME=", line: 'JBOSS_HOME="/home/ec2-user/opt/jboss-eap-7.4.0"'}
        - {regexp: "^# JBOSS_USER=", line: 'JBOSS_USER=jboss-user'}

    - name: Update /etc/profile with JBOSS_HOME variable
      lineinfile:
        path: /etc/profile
        state: present
        line: "{{ item }}"
      with_items:
        - 'export JBOSS_HOME="/home/ec2-user/opt/jboss-eap-7.4.0"'
        - 'export PATH=$PATH:$JBOSS_HOME/bin'

    - name: Configure JBoss EAP as a service
      command:
        chdir: /home/ec2-user/opt/jboss-eap-7.4.0
        cmd: "{{item }}"
      with_items:
        - cp /home/ec2-user/opt/jboss-eap-7.4.0/bin/init.d/jboss-eap.conf /etc/default/
        - cp /home/ec2-user/opt/jboss-eap-7.4.0/bin/init.d/jboss-eap-rhel.sh /etc/init.d/
        - restorecon /etc/init.d/jboss-eap-rhel.sh
        - chkconfig --add jboss-eap-rhel.sh 

    - name: Start JBoss EAP Service
      service:
        name: jboss-eap-rhel
        state: started
        enabled: yes
